---
desktop_packages:
- chromium
- firefox-wayland
#- gnome-shell-extension-pop-shell
- gnome-tweak-tool
- gnome-extensions-app
- mozilla-https-everywhere
- mozilla-noscript
- mozilla-ublock-origin
- gnome-epub-thumbnailer
- xfreerdp

desktop_fontconfig:
- /usr/share/fontconfig/conf.avail/10-autohint.conf
- /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
- /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf

desktop_gsettings:
# doesn't work in fedora 34?
#- org.gnome.settings-daemon.plugins.xsettings antialiasing rgba
# doesn't work in fedora 34?
#- org.gnome.settings-daemon.plugins.xsettings hinting slight
#- org.gnome.desktop.interface text-scaling-factor 1.25
- org.gnome.desktop.interface clock-format 12h
- org.gnome.desktop.interface clock-show-date true
- org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
# fractional scaling and screen share (pipewire)
- org.gnome.mutter experimental-features "['scale-monitor-framebuffer', 'screen-cast', 'remote-desktop']"
