- name: install packages
  dnf:
    name: '{{ arduino_packages }}'
    state: present
  become: yes
  tags:
  - arduino

- name: add user to groups
  user:
    name: '{{ username }}'
    groups: dialout,lock
    append: yes
  become: yes
  tags:
  - arduino
