---
- name: turn off systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: yes
  tags:
  - network

- name: check if resolv.conf is symlink (systemd)
  stat:
    path: /etc/resolv.conf
  register: st
  become: yes
  tags:
  - network

- name: remove resolv.conf if symlink (systemd)
  file:
    path: /etc/resolv.conf
    state: absent
  when: st.stat.islnk
  register: resolv
  become: yes
  tags:
  - network

- name: enable dnsmasq for NetworkManager
  copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    owner: root
    group: root
    mode: 0644
    content: |
      [main]
      dns=dnsmasq
  register: dnsmasq
  become: yes
  tags:
  - network

# FIXME: race condition where symlink is gone and dns fails on next
# play. We need to restart here if it has changed.
#
- name: restart network manager
  service:
    name: NetworkManager
    state: restarted
  when: resolv.changed or dnsmasq.changed
  register: networkmanager
  become: yes
  tags:
  - network

- name: pause if networkmanager is restarted
  ansible.builtin.pause:
    seconds: 10
  when: networkmanager.changed
  tags:
  - network
