---
- name: turn off systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: yes
  tags:
  - network

- name: check if resolv.conf is symlink (systemd)
  stat:
    path: /etc/resolv.conf
  register: st
  become: yes
  tags:
  - network

- name: remove resolv.conf if symlink (systemd)
  file:
    path: /etc/resolv.conf
    state: absent
  when: st.stat.islnk
  become: yes
  tags:
  - network

- name: enable dnsmasq for NetworkManager
  copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    owner: root
    group: root
    mode: 0644
    content: |
      [main]
      dns=dnsmasq
  become: yes
  notify:
  - restart NetworkManager
  tags:
  - network
