---

- name: install packages
  ansible.builtin.package:
    name: "{{ libvirt_packages }}"
    state: present
  become: yes
  tags:
  - libvirt

- name: add user to libvirt
  ansible.builtin.user:
    name: "{{ username }}"
    groups: libvirt
    append: yes
  become: yes
  tags:
  - libvirt
